---
- name: Detach volume from EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    region: ap-south-1
    volume_id: vol-0aeb82b96c731e695

  tasks:
    - name: Detach volume
      ec2_vol:
        region: "{{ region }}"
        volume_id: "{{ volume_id }}"
        state: absent
